server:
  port: 21000
spring:
  rabbitmq:
    host: 8.134.177.106
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        # 开启手动ack
        acknowledge-mode: manual
        # 每次获取10条消息进行消费
        prefetch: 10
    # 开启Confirm机制
    publisher-confirm-type: correlated
    # 开启Return机制
    publisher-returns: true
  datasource:
    url: jdbc:mysql://8.134.177.106:3306/practice_demo?serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf-8&characterSetResults=UTF-8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: starbug-docker-mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:*/mappers/*.xml
